version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:651975211405:task-definition/benchmark-td:1"
        LoadBalancerInfo:
          ContainerName: "mfpe-module"
          ContainerPort: "9093"
        PlatformVersion: "LATEST"
